### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [CoreSkywalker/PZRL_LAB#1]
1. Не обрабатывается часть ошибочных ситуаций.
![изображение](https://github.com/CoreSkywalker/PZRL_LAB/assets/36138085/84f824ec-0401-4585-94b3-19136d819ead)
![изображение](https://github.com/CoreSkywalker/PZRL_LAB/assets/36138085/07f3baf1-055c-422c-9c4a-06efc9ecc33b)
2. Неправильный формат вывода в восьмеричной системе счисления.
![изображение](https://github.com/CoreSkywalker/PZRL_LAB/assets/36138085/5443d49c-27ca-4461-a19e-ab884900036e)
3. Ошибка при вычислении/выводе.
![изображение](https://github.com/CoreSkywalker/PZRL_LAB/assets/36138085/d7869998-2dce-449a-8c94-b57d296d2f9e)
4. В Makefile не реализована инкрементная сборка. Да и вообще - там много ошибок. Переделайте.

**Comment by CoreSkywalker** [comment]
Обновил.

**Comment by rredbird66** [comment]
1. Ещё одна некорректная операция. Ну вы б все проверили сначала, на всякий случай, а не только те, которые я нашёл.
![изображение](https://github.com/CoreSkywalker/PZRL_LAB/assets/36138085/e1169e43-3363-4d78-bd52-8c92065c7ce5)
4. Инкрементная сборка в make всё ещё не реализована. Ну реквизиты целям укажите то. Если файлы исходного кода поменяются - make не станет пересобирать объектные, а должен.

**Comment by CoreSkywalker** [comment]
Починил, должно работать)

**Comment by rredbird66** [comment]
Небольшое замечание по сборке. Почитайте, на каком этапе сборки к программе "подсоединяются" библиотеки, на всякий случай. Могу на зачёте припомнить.
Лабораторная работа 2 зачтена.
